
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionEtudiantWS", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionEtudiantWS {


    /**
     * 
     * @param nom
     * @param prenom
     */
    @WebMethod(operationName = "AjouterEtudiants")
    @RequestWrapper(localName = "AjouterEtudiants", targetNamespace = "http://Service/", className = "service.AjouterEtudiants")
    @ResponseWrapper(localName = "AjouterEtudiantsResponse", targetNamespace = "http://Service/", className = "service.AjouterEtudiantsResponse")
    @Action(input = "http://Service/GestionEtudiantWS/AjouterEtudiantsRequest", output = "http://Service/GestionEtudiantWS/AjouterEtudiantsResponse")
    public void ajouterEtudiants(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom);

    /**
     * 
     * @param id
     * @param nom
     * @param prenom
     */
    @WebMethod(operationName = "ModifierEtudiants")
    @RequestWrapper(localName = "ModifierEtudiants", targetNamespace = "http://Service/", className = "service.ModifierEtudiants")
    @ResponseWrapper(localName = "ModifierEtudiantsResponse", targetNamespace = "http://Service/", className = "service.ModifierEtudiantsResponse")
    @Action(input = "http://Service/GestionEtudiantWS/ModifierEtudiantsRequest", output = "http://Service/GestionEtudiantWS/ModifierEtudiantsResponse")
    public void modifierEtudiants(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom);

    /**
     * 
     * @param id
     */
    @WebMethod(operationName = "SupprimerEtudiants")
    @RequestWrapper(localName = "SupprimerEtudiants", targetNamespace = "http://Service/", className = "service.SupprimerEtudiants")
    @ResponseWrapper(localName = "SupprimerEtudiantsResponse", targetNamespace = "http://Service/", className = "service.SupprimerEtudiantsResponse")
    @Action(input = "http://Service/GestionEtudiantWS/SupprimerEtudiantsRequest", output = "http://Service/GestionEtudiantWS/SupprimerEtudiantsResponse")
    public void supprimerEtudiants(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     */
    @WebMethod(operationName = "ListerEtudiants")
    @RequestWrapper(localName = "ListerEtudiants", targetNamespace = "http://Service/", className = "service.ListerEtudiants")
    @ResponseWrapper(localName = "ListerEtudiantsResponse", targetNamespace = "http://Service/", className = "service.ListerEtudiantsResponse")
    @Action(input = "http://Service/GestionEtudiantWS/ListerEtudiantsRequest", output = "http://Service/GestionEtudiantWS/ListerEtudiantsResponse")
    public void listerEtudiants();

}
