
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionEtudiantWS", targetNamespace = "http://Service/", wsdlLocation = "http://localhost:8585/GestionEtudiantWS?wsdl")
public class GestionEtudiantWS_Service
    extends Service
{

    private final static URL GESTIONETUDIANTWS_WSDL_LOCATION;
    private final static WebServiceException GESTIONETUDIANTWS_EXCEPTION;
    private final static QName GESTIONETUDIANTWS_QNAME = new QName("http://Service/", "GestionEtudiantWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/GestionEtudiantWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONETUDIANTWS_WSDL_LOCATION = url;
        GESTIONETUDIANTWS_EXCEPTION = e;
    }

    public GestionEtudiantWS_Service() {
        super(__getWsdlLocation(), GESTIONETUDIANTWS_QNAME);
    }

    public GestionEtudiantWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONETUDIANTWS_QNAME, features);
    }

    public GestionEtudiantWS_Service(URL wsdlLocation) {
        super(wsdlLocation, GESTIONETUDIANTWS_QNAME);
    }

    public GestionEtudiantWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONETUDIANTWS_QNAME, features);
    }

    public GestionEtudiantWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionEtudiantWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionEtudiantWS
     */
    @WebEndpoint(name = "GestionEtudiantWSPort")
    public GestionEtudiantWS getGestionEtudiantWSPort() {
        return super.getPort(new QName("http://Service/", "GestionEtudiantWSPort"), GestionEtudiantWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionEtudiantWS
     */
    @WebEndpoint(name = "GestionEtudiantWSPort")
    public GestionEtudiantWS getGestionEtudiantWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service/", "GestionEtudiantWSPort"), GestionEtudiantWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONETUDIANTWS_EXCEPTION!= null) {
            throw GESTIONETUDIANTWS_EXCEPTION;
        }
        return GESTIONETUDIANTWS_WSDL_LOCATION;
    }

}
